aliases:
  andreia:
  - andrea
  - andria
  - andréia
  - andréa
  - andreá
  andréa:
  - andreia
  - andrea
  - andréia
boosts:
  department:
    biologia: 1.1
    computacao: 1.15
    dtad: 1.25
    dti: 1.3
    psicologia: 1.05
    stpg: 1.35
departments:
  administracao: Administração
  biologia: Departamento de Ciências Biológicas
  computacao: Departamento de Computação
  congregacao: Congregação
  diretoria_academica: Diretoria Tecnica Academica
  diretoria_administrativa: Diretoria Tecnica Administrativa
  dtad: Diretoria Tecnica Administrativa
  dti: Diretoria Tecnica de Informatica
  educacao: Departamento de Educação
  educacaofisica: Departamento de Educação Física
  fisica: Departamento de Física e Meteorologia
  ldc: Laboratorio Didatico Computacional
  matematica: Departamento de Matemática
  psicologia: Departamento de Psicologia
  quimica: Departamento de Química
  staepe: Seção Técnica de Apoio ao Ensino, Pesquisa e Extensão
  stgp: Seção Técnica de Gestão de Pessoas
  stpg: Secao Tecnica de Pos-Graduacao
keywords:
- agendamento
- anfiteatro
- auxílios
- bolsas
- capes
- cnpq
- colação de grau
- cotas
- eduroam
- enade
- fapesp
- impressao
- ldc
- moradia estudantil
- papercut
- plotter
- reserva
- saad
- stpg
- vestibular
- vunesp
synonyms:
  anfiteatro: Anfiteatro da Pos-Graduacao
  bcc: Bacharelado em Ciência da Computação
  bsi: Bacharelado em Sistemas de Informação
  compras: Seção Técnica de Materiais
  cope: Coordenadoria de Permanência Estudantil
  cotas: Cotas de impressao
  dco: Departamento de Computação
  def: Departamento de Educação Física
  dpsi: Departamento de Psicologia
  dta: Diretoria Técnica Acadêmica
  dtad: Diretoria Técnica Administrativa
  faac: Faculdade de Arquitetura, Artes e Comunicação
  feb: Faculdade de Engenharia de Bauru
  financas: Seção Técnica de Finanças
  fundeb: FUNDEB
  impressao: Servico de Impressao
  ipmet: IPMET
  lab: Laboratorio
  ldc: Laboratorio Didatico Computacional
  lepec: Laboratorio de Ensino, Pesquisa e Extensao em Computacao
  proex: Pró-Reitoria de Extensão Universitária
  prof: Professor
  prof: Professora
  prograd: Pró-reitoria de Graduação
  prope: Pró-reitoria de Pesquisa
  psico: Psicologia
  reserva: Reserva de espacos academicos
  rh: Recursos Humanos / Seção Técnica de Gestão de Pessoas
  saad: Secao de Apoio Administrativo
  sta: Seção Técnica Acadêmica
  stf: Seção Técnica de Finanças
  stg: Seção Técnica de Graduação
  stm: Seção Técnica de Materiais
  stpg: Secao Tecnica de Pos-Graduacao
  voip: Telefonia VoIP
  
  
